name: Run tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packages
        uses: oven-sh/setup-bun@v2
        run: bun install

      - name: Run build
        run: bun run build

      - name: Run tests
        run: bun run test
